baseURL: "https://21dejunio.org"
languageCode: "en-us"
title: "21 de junio - Centro de Estudiantes de Humanidades y Ciencias de la Educación - ASCEEP - FEUU"
pygmentsstyle: 'monokai'

# Theme settings
theme: novela
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
